name: loja_virtual_mind
description: A new Flutter project for Loja Mind.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0 # Para persistir dados do usuário localmente (como localStorage)
  provider: ^6.0.5 # Para gerenciamento de estado (carrinho, usuário logado)
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/images/blusão_mind.jpg
    - assets/images/calca_jeans_escura.jpg
    - assets/images/relogio_esportivo.jpg
    - assets/images/vestido_vermelho.jpg
    - assets/images/camiseta_stret_mind.jpg
    - assets/images/blusa_floral.jpg
    - assets/images/saia_streat.jpg
    - assets/images/bolsa_couro.jpg
    - assets/images/tenis_running.jpg
    - assets/images/relogio_digital.jpg
    - assets/images/bone_bulls.jpg
    - assets/images/blusa_unissex.jpg



  